server:
  port: 8081

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: learninge452@gmail.com
    password: cudpeeulxrpjdgak
    properties:
      mail:
        smtp:
          auth : true
          starttls:
            enable : true
  datasource:
    url: jdbc:postgresql://localhost:5432/tagardedb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 30000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "Initial version"
    baseline-version: 0
    locations: classpath:db/migration

