spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tagardedb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    tagarde: DEBUG